POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "New note",
  "important": false
}


###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Another note",
  "important": true
}


###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Yet another note to mongodb",
  "important": true
}